webtalk_init -webtalk_dir C:\\Users\\PC-CLICK-PLUS\\stage\\vitis\\prj_counter_interrupt\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-09-04 15:44:06" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212720095_0_0_107" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5bn8kpm8ghdrt5382mggnuulpo" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_33" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "33" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.490 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1725453705597" -context "vitis\\\\platform/1725453705597"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1725453705597"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1725453705597"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1725453705597"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1725453705597"
webtalk_add_data -client vitis -key uid -value "1725453794042" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key processor -value "cortex-a9" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key template -value "sdk" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key device_family -value "zynq" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key fpga -value "xc7z020" -context "vitis\\\\application/1725453794042"
webtalk_add_data -client vitis -key uid -value "1725456833520" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key processor -value "cortex-a9" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key template -value "empty" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key device_family -value "zynq" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key fpga -value "xc7z020" -context "vitis\\\\application/1725456833520"
webtalk_add_data -client vitis -key uid -value "NA" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key RecordType -value "ToolUsage" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key BOOTGEN_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key FLASH_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key MOVE_APP_TO_SYSTEM_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key SDX_EXPORT_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key SDX_IMPORT_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key SDX_BUILD_count -value "1" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key SDX_NO_OP_BUILD_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key TCF_APP_DEBUG_count -value "6" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key TCF_SYSTEM_DEBUG_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key GDB_DEBUG_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key QEMU_DEBUG_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key ESTIMATION_DEBUG_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key SDSOC_TRACE_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key PERFORMANCE_ANALYSIS_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key SPM_ANALYSIS_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key CROSS_TRIGGER_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key TCF_PROFILER_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key APPLICATION_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key APPLICATION_SYS_CONFIG_CHANGE_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_add_data -client vitis -key SYSTEM_PLATFORM_CHANGE_count -value "0" -context "vitis\\\\tool/1725461046842"
webtalk_transmit -clientid 2252638034 -regid "212720095_0_0_107" -xml C:\\Users\\PC-CLICK-PLUS\\stage\\vitis\\prj_counter_interrupt\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\Users\\PC-CLICK-PLUS\\stage\\vitis\\prj_counter_interrupt\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\Users\\PC-CLICK-PLUS\\stage\\vitis\\prj_counter_interrupt\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
