webtalk_init -webtalk_dir C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_jstk2_oledRGB\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-09-22 16:06:19" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212720095_0_0_107" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bl9o2cmv1febpiaoo2dkh8irmg" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_50" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "50" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.490 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1727011987076" -context "vitis\\\\platform/1727011987076"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1727011987076"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1727011987076"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1727011987076"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1727011987076"
webtalk_add_data -client vitis -key uid -value "1727012055505" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key project_type -value "sdk" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key processor -value "cortex-a9" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key runtime -value "C/C++" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key template -value "empty" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key platform -value "custom" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key platform_type -value "fixed" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key application_type -value "application" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key platform_source -value "platform" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key device_family -value "zynq" -context "vitis\\\\application/1727012055505"
webtalk_add_data -client vitis -key fpga -value "xc7z020" -context "vitis\\\\application/1727012055505"
webtalk_transmit -clientid 2288138760 -regid "212720095_0_0_107" -xml C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_jstk2_oledRGB\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_jstk2_oledRGB\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_jstk2_oledRGB\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
