webtalk_init -webtalk_dir C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_robot_wifi_jstk_trans\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-09-24 15:26:56" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vitis v2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212720095_0_0_107" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "Vitis" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "50fkmuqk7vtekg2r33koal61nd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.2_53" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "53" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.490 GB" -context "user_environment"
webtalk_register_client -client vitis
webtalk_add_data -client vitis -key uid -value "1727184717274" -context "vitis\\\\platform/1727184717274"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1727184717274"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1727184717274"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1727184717274"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1727184717274"
webtalk_add_data -client vitis -key uid -value "1727185602148" -context "vitis\\\\platform/1727185602148"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1727185602148"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1727185602148"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1727185602148"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1727185602148"
webtalk_add_data -client vitis -key uid -value "1727187428313" -context "vitis\\\\platform/1727187428313"
webtalk_add_data -client vitis -key platform_source -value "dsa" -context "vitis\\\\platform/1727187428313"
webtalk_add_data -client vitis -key os -value "standalone" -context "vitis\\\\platform/1727187428313"
webtalk_add_data -client vitis -key processor -value "ps7_cortexa9" -context "vitis\\\\platform/1727187428313"
webtalk_add_data -client vitis -key platform -value "NA" -context "vitis\\\\platform/1727187428313"
webtalk_transmit -clientid 490051757 -regid "212720095_0_0_107" -xml C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_robot_wifi_jstk_trans\\webtalk\\usage_statistics_ext_vitis.xml -html C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_robot_wifi_jstk_trans\\webtalk\\usage_statistics_ext_vitis.html -wdm C:\\Users\\PC-CLICK-PLUS\\Desktop\\Stage_CRTI\\vitis\\prj_robot_wifi_jstk_trans\\webtalk\\vitis_webtalk.wdm -intro "<H3>Vitis Usage Report</H3><BR>"
webtalk_terminate
